import Brand from './brand';
import React,{useState} from 'react';
import ReactDOMServer from 'react-dom/server';
import DocumentManager from './gapi/DocumentManager.js';
import DocWriter from './gapi/docWriter.js';
import {Card,h,ProgressOverlay,Buttons,Button,Modal,Icon} from './widgets.js';

function DocExporter (props) {

    const [showRendered,setShowRendered] = useState(false)
    const [link,setLink] = useState()
    const [status,setStatus] = useState()
    const [showShare,setShowShare] = useState();
    const [sendEmail,setSendEmail] = useState(true);
    const [shareMessage,setShareMessage] = useState(`Please review this document: ${props.docTitle}.\n\nThis document was generated by ${Brand.shortname}. To make changes to your reflections or submit revisions, please access ${Brand.name} directly at ${Brand.url} rather than editing this google doc as the document may be overwritten in the future.`);

    async function doExport () {
        setStatus('Writing portfolio...')
        var body = ReactDOMServer.renderToString(
            <html>
              <head>
                <title>{props.docTitle}</title>
              </head>
              <body>                                                     
                {props.children}
              </body>
            </html>);
        
        setStatus('Looking to see if a document exists already...');
        var dm = DocumentManager();
        var existingId = await dm.getSheetId(props.course.id,
                                             props.docProp,
                                             props.student && props.student.userId);
        var result;
        if (existingId) {
            setStatus('Found document. Updating document with new portfolio.');
            try {
                result = await DocWriter.updateFile(existingId,
                                                    {description:props.docDescription,
                                                     body:body}
                                                   )
            }
            catch (err) {
                console.log('ERROR: ',err);
                setStatus('Error!');
                window.setTimeout(()=>setStatus(),1000)
                return;
            }
        }
        else {
            setStatus('Exporting portfolio to docs...')
            try {
                result = await  DocWriter.createFile(
                    {title:props.docTitle,
                     description:'A sample portfolio',
                     body:body}
                );
                setStatus('Saving file info for future reference...')
                await dm.addMetadataToFile(
                    result.id,
                    props.course,
                    props.docProp,
                    props.student
                );
            }
            catch (err) {
                console.log('ERROR: ',err);
                setStatus('Error!');
                window.setTimeout(()=>setStatus(),1000)
                return;
            }
        }
        setStatus()
        setLink(result.url)
    }
    
    async function doShare () {
        setShowShare(false);
        setStatus('Finding document to share...');
        var dm = DocumentManager();
        var existingId = await dm.getSheetId(props.course.id,
                                             props.docProp,
                                             props.student && props.student.userId);
        if (!existingId) {
            throw 'No document to share';
        }
        setStatus(`Found document - sharing with ${props.student.profile.emailAddress}`);
        await dm.shareFile(existingId,props.student,
                           {
                               email : shareMessage
                           }
                          );
        setStatus(`Document shared successfully with  ${props.student.profile.emailAddress}!`);
        window.setTimeout(()=>setStatus(),1000);
    }


    return <ProgressOverlay active={status}>
               <Buttons>
                 <Button className="is-secondary is-light" onClick={()=>setShowRendered(!showRendered)}>Preview</Button>
                 {props.mode=='teacher' && link && <Button className='is-secondary is-light' onClick={()=>setShowShare(!showShare)}>Share</Button>}
                 <Button className="is-info is-light" onClick={doExport}>{props.buttonText||"Export to Doc"}</Button>
                 {link && <Button href={link} target="_BLANK" icon={Icon.external}>See Export</Button>}
                 {props.mode=='teacher' && link && <Modal active={showShare} onClose={()=>setShowShare(false)}>
                   <Card>
                     <h.h2>Share Document with {props.student.profile.name.fullName}</h.h2>
                     <div>
                       <div><label><Button.Toggle active={sendEmail} onClick={()=>setSendEmail(!sendEmail)}/> Share Email</label></div>
                       <div>{sendEmail && <label>
                                       <strong>Message</strong>
                                       <textarea
                                         className='textarea'
                                         onChange={(e)=>setShareMessage(e.target.value)}
                                         value={shareMessage}
                                       />
                             </label>}
                       </div>
                     </div>
                     <Buttons>
                       <Button icon={Icon.close} onClick={()=>setShowShare(false)}>Close</Button>
                       <Button icon={Icon.share} onClick={doShare}>Share</Button>
                     </Buttons>

                   </Card>
                          </Modal>}
                 <Modal className='full' active={showRendered} onClose={()=>setShowRendered(false)}>
                   <div style={{margin:'auto',
                                width:'468pt'}}>
                     {props.children}
                   </div>
                 </Modal>
               </Buttons>
               <p>{status}</p>
             </ProgressOverlay>

}
export default DocExporter;
